---
- name: include vars
  include_vars: ../../../group_vars/all

- name: Download pip...
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/root/

- name: Install pip...
  command: "python /root/get-pip.py"
  become: yes

- name: Install httplib2
  pip: name=httplib2 state=present

- name: Starting Policy Enforcement For Simple Cluster...
  include: plugin_enf.yml
  when: '{{ is_kerberos|lower }} == false'

- name: Starting Policy Enforcement For Kerberized Cluster...
  include: plugin_enf_krb.yml
  when: '{{ is_kerberos|lower }} == true'
